### ISSUE TITLE
Improve on `InMemoryStorage` proposals

### ISSUE THREAD

**Issue by alexsnaps** [Kuadrant/limitador#70]
Adding this as a dumping ground for ideas of possible improvements we could implement to make `InMemoryStorage` more memory efficient and made more parallel:

 - [ ] Have #69 
 - [x] "variadic" counters with interior mutability? (so to only grow the `Set` under write lock)
 - [x] Get rid of the `TtlCache<Counter, i64>` and store counters in something like `NonBlockingCounter` (see #71)
 - [x] Possibly avoid duplication of data (e.g. `Counter.limit`, have Limit being composed of Counters instead)… i.e. remodel things to match the reality of the domain, not the persistence of it. Possibly relates to #74 
 - [ ] Should we make this a hierarchical storage? One where counters would always sit in memory, certainly for short-lived counters (seconds/minutes, possibly configurable) where persistence make little sense
